
variable "autounattend" {
  type    = string
  default = "windows_utils/answer_files/2016/Autounattend.xml"
}

variable "esxi_datastore" {
  type    = string
  default = ""
}

variable "esxi_host" {
  type    = string
  default = ""
}

variable "esxi_password" {
  type    = string
  default = ""
}

variable "esxi_username" {
  type    = string
  default = ""
}

variable "esxi_network_with_dhcp_and_internet" {
  type    = string
  default = ""
}

variable "iso_checksum" {
  type    = string
  default = "md5:70721288BBCDFE3239D8F8C0FAE55F1F"
}

variable "iso_url" {
  type    = string
  default = "https://software-download.microsoft.com/download/pr/Windows_Server_2016_Datacenter_EVAL_en-us_14393_refresh.ISO"
}

source "vmware-iso" "autogenerated_1" {
  boot_wait           = "2m"
  communicator        = "winrm"
  disk_size           = 16000
  floppy_files        = ["${var.autounattend}", "windows_utils/floppy/WindowsPowershell.lnk", "windows_utils/floppy/PinTo10.exe", "windows_utils/scripts/unattend.xml", "windows_utils/scripts/sysprep.bat", "windows_utils/scripts/disable-screensaver.ps1", "windows_utils/scripts/disable-winrm.ps1", "windows_utils/scripts/enable-winrm.ps1", "windows_utils/scripts/microsoft-updates.bat", "windows_utils/scripts/win-updates.ps1"]
  guest_os_type       = "windows8srv-64"
  headless            = false
  insecure_connection = true
  iso_checksum        = "${var.iso_checksum}"
  iso_url             = "${var.iso_url}"
  keep_registered     = true
  remote_datastore    = "${var.esxi_datastore}"
  remote_host         = "${var.esxi_host}"
  remote_password     = "${var.esxi_password}"
  remote_type         = "esx5"
  remote_username     = "${var.esxi_username}"
  shutdown_command    = "a:/sysprep.bat"
  shutdown_timeout    = "2h"
  skip_export         = true
  version             = 11
  vm_name             = "WindowsServer2016"
  vmx_data = {
    "ethernet0.networkName"          = "${var.esxi_network_with_dhcp_and_internet}"
  }
  vnc_disable_password = true
  vnc_over_websocket   = true
  winrm_password       = "vagrant"
  winrm_timeout        = "4h"
  winrm_username       = "vagrant"
}

build {
  sources = ["source.vmware-iso.autogenerated_1"]

  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    scripts         = ["windows_utils/scripts/vm-guest-tools.bat", "windows_utils/scripts/enable-rdp.bat"]
  }

  provisioner "powershell" {
    scripts = ["windows_utils/scripts/debloat-windows.ps1"]
  }

  provisioner "windows-restart" {
  }

  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    scripts         = ["windows_utils/scripts/pin-powershell.bat", "windows_utils/scripts/set-winrm-automatic.bat", "windows_utils/scripts/compile-dotnet-assemblies.bat", "windows_utils/scripts/uac-enable.bat", "windows_utils/scripts/compact.bat"]
  }

}
