
variable "autounattend" {
  type    = string
  default = "windows_utils/answer_files/10/Autounattend.xml"
}

variable "esxi_datastore" {
  type    = string
  default = ""
}

variable "esxi_host" {
  type    = string
  default = ""
}

variable "esxi_password" {
  type    = string
  default = ""
}

variable "esxi_username" {
  type    = string
  default = ""
}

variable "iso_checksum" {
  type    = string
  default = "sha256:ab4862ba7d1644c27f27516d24cb21e6b39234eb3301e5f1fb365a78b22f79b3"
}

variable "esxi_network_with_dhcp_and_internet" {
  type    = string
  default = ""
}

variable "iso_url" {
  type    = string
  default = "https://software-download.microsoft.com/download/pr/18362.30.190401-1528.19h1_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso"
}

source "vmware-iso" "autogenerated_1" {
  boot_command        = ""
  boot_wait           = "10m"
  communicator        = "winrm"
  disk_size           = 30000
  floppy_files        = ["${var.autounattend}", "windows_utils/floppy/WindowsPowershell.lnk", "windows_utils/floppy/PinTo10.exe", "windows_utils/scripts/fixnetwork.ps1", "windows_utils/scripts/rearm-windows.ps1", "windows_utils/scripts/disable-screensaver.ps1", "windows_utils/scripts/disable-winrm.ps1", "windows_utils/scripts/enable-winrm.ps1", "windows_utils/scripts/microsoft-updates.bat", "windows_utils/scripts/win-updates.ps1", "windows_utils/scripts/unattend.xml", "windows_utils/scripts/sysprep.bat"]
  guest_os_type       = "windows9-64"
  headless            = false
  insecure_connection = true
  iso_checksum        = "${var.iso_checksum}"
  iso_url             = "${var.iso_url}"
  keep_registered     = true
  remote_datastore    = "${var.esxi_datastore}"
  remote_host         = "${var.esxi_host}"
  remote_password     = "${var.esxi_password}"
  remote_type         = "esx5"
  remote_username     = "${var.esxi_username}"
  shutdown_command    = "a:/sysprep.bat"
  shutdown_timeout    = "2h"
  skip_export         = true
  version             = 11
  vm_name             = "Windows10"
  vmx_data = {
    "ethernet0.networkName"          = "${var.esxi_network_with_dhcp_and_internet}"
  }
  vnc_disable_password = true
  vnc_over_websocket   = true
  vnc_port_max         = 5980
  vnc_port_min         = 5900
  winrm_password       = "vagrant"
  winrm_timeout        = "4h"
  winrm_username       = "vagrant"
}

build {
  sources = ["source.vmware-iso.autogenerated_1"]

  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    remote_path     = "/tmp/script.bat"
    scripts         = ["windows_utils/scripts/vm-guest-tools.bat", "windows_utils/scripts/enable-rdp.bat"]
  }

  provisioner "powershell" {
    scripts = ["windows_utils/scripts/debloat-windows.ps1"]
  }

  provisioner "windows-restart" {
  }

  provisioner "powershell" {
    scripts = ["windows_utils/scripts/set-powerplan.ps1", "windows_utils/scripts/docker/disable-windows-defender.ps1"]
  }

  provisioner "windows-shell" {
    execute_command = "{{ .Vars }} cmd /c \"{{ .Path }}\""
    remote_path     = "/tmp/script.bat"
    scripts         = ["windows_utils/scripts/pin-powershell.bat", "windows_utils/scripts/compile-dotnet-assemblies.bat", "windows_utils/scripts/set-winrm-automatic.bat", "windows_utils/scripts/dis-updates.bat"]
  }

}
